---
 - hosts: localhost
   tasks:
     - name: Install custom sets
       ansible.builtin.copy:
         src: "portage-sets/{{ item }}"
         dest: '/etc/portage/sets/'
         owner: portage
         group: portage
         mode: u=rw,g=r,o=r
       with_items:
         - dwl
         - athens
